# All paths are relative to project root
DATA_FOLDER: 'data'
NEWS_FOLDER: 'data/multi-modal-dataset/sp500_news'
TIMES_SERIES_FOLDER: 'data/multi-modal-dataset/sp500_time_series'
DATA_DICTIONARY: 'data/multi-modal-dataset/sp500stock_data_description.csv'
STOCK_SCORE_NEWS: 'data/multi-modal-dataset/stock_scores_news_1.csv'
TABULAR_DATA: 'data/multi-modal-dataset/sp500_table'

