DATA_FOLDER: '../data'
NEWS_FOLDER: '../data/multi-modal-dataset/sp500_news'
DATA_DICTIONARY: '../data/multi-modal-dataset/sp500stock_data_description.csv'

STOCK_DATA_FOLDER: '../data/S&P500_time_series'
ANALYSIS_FOLDER: '../data/analysis_results'
UTILS_FOLDER: './utils'


YOY_ANALYSIS_FILE: '../data/analysis_results/yoy_analysis_full.csv'
YEARLY_SUMMARY_FILE: '../data/analysis_results/yearly_summary_full.csv'
ALL_STOCKS_RANKED_FILE: '../data/analysis_results/all_stocks_ranked.csv'
ALL_STOCKS_RANKED_TXT: '../data/analysis_results/all_stocks_ranked.txt'
